### ISSUE TITLE
Revisar as associações no model Joob

### ISSUE THREAD

**Issue by mvoto** [phillip18/Job_Board#1]
Onde você tem:

```
class Joob < ApplicationRecord
	has_many :comment
	validates_presence_of :title, :description, :premium
	accepts_nested_attributes_for :comment
end
```

O seu has_many, seria bacana utilizar `has_many :comments`
Acho também que esse `accepts_nested_attributes_for` não é mais necessário.

**Comment by phillip18** [comment]
Mauricio, alterei tudo onde estava comment para comments. o accepts_nested_attributes_for :comment foi um teste, não era necessário mesmo.
