### ISSUE TITLE
Parâmetros do SQL

### ISSUE THREAD

**Issue by phillip18** [phillip18/Job_Board#5]
Verifiquei que a consulta há duas diferenças para a consulta do curso:
- LIMIT 1 em vez de LIMIT ?
- [["id", 5], ["LIMIT", 1]]
Meu Código:
Joob Load (0.3ms)  SELECT  "joobs".* FROM "joobs" WHERE "joobs"."id" = ? LIMIT ?  [["id", 5], ["LIMIT", 1]]

Código do curso:

![image](https://cloud.githubusercontent.com/assets/19421621/17036888/a15f7106-4f64-11e6-98c7-4e7c4ecd6ed9.png)

**Comment by mvoto** [comment]
Cara, estou um pouco enrolado no meu trampo agora, assim que eu conseguir, eu vou baixar o teu projeto e rodar local aqui para entender melhor o que está acontecendo no momento do create comment.

**Comment by phillip18** [comment]
Tranquilo brother, já sou muito grato pela sua disponibilidade em me ajudar!
